name: DevOps Challenge 

on:

  push:
    branches: [ main ]

jobs:
  
  build:

    runs-on: ubuntu-latest
    
    steps:

      - uses: actions/checkout@v3
      
      - name: version
        id: version
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INITIAL_VERSION: 0.0.0
          WITH_V: true
          
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github 
          settings-path: ${{ github.workspace }} 

      - name: Build with Maven
        run: mvn clean package 

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
      
      - name: Create a Release
        uses: elgohr/Github-Release-Action@v4 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     
        with:
          title: "${{ steps.version.outputs.tag }}"
          
      - name: Create tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
     
