# This is a basic workflow to help you get started with Actions

name: DevOps Challenge 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"

  
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Bumpversion
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INITIAL_VERSION: 0.0.0
          

          
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github 
          settings-path: ${{ github.workspace }} 

      - name: Build with Maven
        run: mvn clean package 

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
      
      - name: Create a Release
        uses: elgohr/Github-Release-Action@v4
         
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
        with:
          title: Application Version ${{ steps.Bumpversion.outputs.tag }}"
            echo '${{ steps.Bumpversion.outputs.tag }}'
            echo '${{ steps.Bumpversion.outputs.new_tag }}'
     
